inquiry_resolution:
  description: >
    {customer} just reached out with a super important ask: 
    
    {inquiry}

    {person} from {customer} is the one that reached out. 
    Make sure to use everything you know to provide a basic level of support.
    You must strive to fast basic responses to the customer's inquiry.
  expected_output: >
    A brief, rapid but informative response to the 
    customer's inquiry that addresses all aspects of their question.

    The response should include references to everything you used to find the answer, 
    including external data or solutions. Ensure the answer is complete, 
    leaving no questions unanswered, and maintain a helpful and friendly tone throughout.
